### ISSUE TITLE
工程改成库后sync会报错

### ISSUE THREAD

**Issue by iamZ2z** [xiedong11/flutter_app#2]
把boolean isLibrary改成true后，sync project会报错

A problem occurred evaluating root project 'android'.
> A problem occurred configuring project ':app'.
   > Could not resolve all dependencies for configuration ':app:embed'.
      > Could not resolve project :path_provider_linux.
        Required by:
            project :app
         > Project :app declares a dependency from configuration 'embed' to configuration 'default' which is not declared in the descriptor for project :path_provider_linux.
      > Could not resolve project :shared_preferences_web.
        Required by:
            project :app
         > Project :app declares a dependency from configuration 'embed' to configuration 'default' which is not declared in the descriptor for project :shared_preferences_web.
      > Could not resolve project :shared_preferences_macos.
        Required by:
            project :app
         > Project :app declares a dependency from configuration 'embed' to configuration 'default' which is not declared in the descriptor for project :shared_preferences_macos.
      > Could not resolve project :path_provider_windows.
        Required by:
            project :app
         > Project :app declares a dependency from configuration 'embed' to configuration 'default' which is not declared in the descriptor for project :path_provider_windows.
      > Could not resolve project :shared_preferences_windows.
        Required by:
            project :app
         > Project :app declares a dependency from configuration 'embed' to configuration 'default' which is not declared in the descriptor for project :shared_preferences_windows.
      > Could not resolve project :shared_preferences_linux.
        Required by:
            project :app
         > Project :app declares a dependency from configuration 'embed' to configuration 'default' which is not declared in the descriptor for project :shared_preferences_linux.

**Comment by iamZ2z** [comment]
报错应该是在把flutter打包成aar中三方依赖地方

if (isLibrary) {
        //TODO 添加fat-aar处理flutter打包成aar中三方依赖
        def flutterProjectRoot = rootProject.projectDir.parentFile.toPath()
        def plugins = new Properties()
        def pluginsFile = new File(flutterProjectRoot.toFile(), '.flutter-plugins')
        if (pluginsFile.exists()) {
            pluginsFile.withReader('UTF-8') { reader -> plugins.load(reader) }
        }
        plugins.each { name, _ ->
            println name
            embed project(path: ":$name", configuration: 'default')
        }
    }

**Comment by Yangzhuren** [comment]
def tipProjects = ["path_provider_macos", "video_player_web", "shared_preferences_linux", "path_provider_linux", "shared_preferences_web", "shared_preferences_macos"]
plugins.each { name, _ ->
        println name
        if (!tipProjects.contains(name)) {
            embed project(path: ":$name", configuration: 'default')
        }
    }

我也碰到了，然后我把报错的依赖跳过了，就可以了，但是这个方案还是会有很多问题。
